proj6: jlenag2proj6.o island.o
	g++ -o proj6 jlenag2proj6.o island.o

jlenag2proj6.o: jlenag2proj6.cpp 
	g++ -c jlenag2proj6.cpp

island.o: island.cpp island.h 
	g++ -c island.cpp

clean:
	rm jlenag2proj5.o island.o  proj6